---
sidebar: sidebar 
permalink: task-manage-volumes.html 
keywords: azure netapp files, delete volumes, delete nfs volumes, netapp account, capacity pool, change service level 
summary: 作業環境をセットアップしたら、 Azure NetApp Files アカウント、容量プール、ボリューム、 Snapshot を管理できます。 
---
= Azure NetApp Files のボリュームを管理します
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
既存のボリュームは、ストレージのニーズの変化に応じて管理できます。ボリュームの編集、ボリュームのサービスレベルの変更、 Snapshot コピーの管理、およびボリュームの削除を行うことができます。



== ボリュームのサイズとタグを編集します

ボリュームの作成後、ボリュームのサイズやタグをいつでも変更できます。

.手順
. 作業環境を開きます。
. ボリュームにカーソルを合わせ、 * 編集 * を選択します。
. 必要に応じてサイズとタグを変更します。
. [ 適用（ Apply ） ] をクリックします。




== ボリュームのサービスレベルを変更します

ボリュームの作成後は、デスティネーション容量プールがすでに存在しているかぎり、いつでもサービスレベルを変更できます。

.手順
. 作業環境を開きます。
. ボリュームにカーソルを合わせ、 * サービスレベルの変更 * を選択します。
. 必要なサービスレベルを提供する容量プールを選択します。
. [ 変更（ Change ） ] をクリックします。


ボリュームは、ボリュームに影響を及ぼすことなく、もう一方の容量プールに移動されます。



== Snapshot コピーを管理します

Snapshot コピーは、ボリュームのポイントインタイムコピーを提供します。Snapshot コピーの作成、新しいボリュームへのデータのリストア、および Snapshot コピーの削除

.手順
. 作業環境を開きます。
. ボリュームにカーソルを合わせ、 Snapshot コピーの管理に使用できるオプションを 1 つ選択します。
+
** * Snapshot コピーを作成します *
** * ボリュームをスナップショットに戻す *
** * Snapshot コピーを削除します。 *


. プロンプトに従って、選択した操作を完了します。




== ボリュームを削除します

不要になったボリュームを削除します。

.手順
. 作業環境を開きます。
. ボリュームにカーソルを合わせ、 * 削除 * をクリックします。
. ボリュームを削除することを確定します。

