---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes' 
summary: Cloud Manager の Azure NetApp Files サポートの新機能について説明します。 
---
= 新機能
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Manager の Azure NetApp Files の新機能について説明します。



== 2021 年 4 月 11 日



=== ボリュームテンプレートのサポート

新しいアプリケーションテンプレートサービスを使用すると、 Azure NetApp Files のボリュームテンプレートを設定できます。テンプレートを使用すると、容量プール、サイズ、プロトコル、 VNet 、ボリュームを配置するサブネットなど、一部のボリュームパラメータがテンプレートにすでに定義されているため、ジョブの簡易化に役立ちます。パラメータがすでに事前定義されている場合は、次のボリュームパラメータに進みます。

* https://docs.netapp.com/us-en/cloud-manager-app-template/concept-resource-templates.html["アプリケーションテンプレートと、環境での使用方法について説明します"^]
* https://docs.netapp.com/us-en/cloud-manager-azure-netapp-files/task-create-volumes.html["テンプレートから Azure NetApp Files ボリュームを作成する方法について説明します"]




== 2021 年 3 月 8 日



=== サービスレベルを動的に変更

ワークロードのニーズを満たし、コストを最適化するために、ボリュームのサービスレベルを動的に変更できるようになりました。ボリュームは、ボリュームに影響を及ぼすことなく、もう一方の容量プールに移動されます。

https://docs.netapp.com/us-en/cloud-manager-azure-netapp-files/task-manage-volumes.html#change-the-volumes-service-level["ボリュームのサービスレベルを変更する方法について説明します"]。



== 2020 年 8 月 3 日



=== Azure NetApp Files のセットアップと管理

Azure NetApp Files は Cloud Manager から直接セットアップおよび管理できます。Azure NetApp Files 作業環境を作成したら、次の作業を実行できます。

* NFS ボリュームと SMB ボリュームを作成
* 容量プールとボリューム Snapshot を管理します
+
Cloud Manager では、ボリューム Snapshot を作成、削除、リストアできます。新しい容量プールを作成してそのサービスレベルを指定することもできます。

* サイズを変更し、タグを管理してボリュームを編集します。


以前のデータ移行機能は、 Cloud Manager から Azure NetApp Files を直接作成および管理できるようになりました。



== 2020 年 4 月 5 日



=== Azure NetApp Files へのデータ移行

NFS または SMB データを Azure NetApp Files に Cloud Manager から直接移行できるようになりました。データの同期には、ネットアップの Cloud Sync サービスが利用されています。
